# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Pirates Radio-T"
license = "MIT"
licenselink = ""
description = "Radio-T Theme"
homepage = "https://pirates.radio-t.com"
tags = ["website"]
features = ["posts", "shortcodes"]
min_version = 0.25

[author]
  name = "Artem Ryabinin"
  homepage = "http://ryabinin.com"
